assets: 
  path: C:/workspaces/datas/
java: 
  path: C:/workspaces/wp_spring/project_uma/app-net/src/main/java/
  packurl: app.uma.net.socket
  packResponse: app.uma.net.socket.decodes.ServerResponse
  packRequest: app.uma.net.socket.decodes.ClientRequest
as: 
  path: C:/workspaces/wp_as/code_client/src/
  packurl: com.icday.database.net
  packResponse: app.uma.net.socket.decodes.ServerResponse
  packRequest: app.uma.net.socket.decodes.ClientRequest