config:
  generateAll: true
  appName: CodeGenerateUtil

assets: 
  data: 
    root: C:/workspaces/datas/
    
code: 
  java: 
    lang: java
    path: C:/workspaces/wp_spring/project_uma/app-net/src/main/java/
    pack: app.uma.net.socket
    requestImport: 
      - app.uma.net.socket.decodes.ServerResponse
    responseImport: 
      - app.uma.net.socket.decodes.ClientRequest
    dataImport: 
      - app.uma.net.socket.decodes.ClientRequest
  as: 
    lang: as
    path: C:/workspaces/wp_as/code_client/src/
    pack: com.icday.database.net
    requestImport: 
      - app.uma.net.socket.decodes.ServerResponse
    responseImport: 
      - app.uma.net.socket.decodes.ClientRequest
    dataImport: 
      - app.uma.net.socket.decodes.ClientRequest