server: 
  port: 9222

spring: 
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/db_uma?characterEncoding=utf8&useSSL=true
    username: admin_uma
    password: zys`123
  session: 
    store-type: none  
  redis:
    host: localhost
    password: zys`123
    port: 6379